### ISSUE TITLE
touch-bar-preview running in background

### ISSUE THREAD

**Issue by jojapps** [touchbar/Touch-Bar-Preview#5]
Is it possible to show the picture in the touch-bar while touch-bar-preview running in background?
Or even better changing the touch-bar background permanently.

**Comment by alexkaessner** [comment]
Sorry but Apple doesn't allow this for now. The macOS automatically manages to show the most active touch bar as Apple states out in the [`NSTouchBar`](https://developer.apple.com/reference/appkit/nstouchbar) Class Reference

> On supported MacBook Pro models, the Touch Bar, above the keyboard, shows instances of the NSTouchBar class from the **front-most** app.
