### ISSUE TITLE
Touch Bar not clearing out esc and other buttons.

### ISSUE THREAD

**Issue by AAAsystems** [touchbar/Touch-Bar-Preview#9]
The program works, except it doesn't clear the default icons out as it says it should.
MBP 13" 2018 if that helps.

**Comment by alexkaessner** [comment]
@AAAsystems Sorry for the misunderstanding, but Touch Bar Preview does not clear the default icons (system buttons). I've updated the readme to better clarify the situation.

As a developer it is actually not possible to hide the esc and system buttons on the right side. Only the user can hide the system buttons via the system preferences.
